#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { parseSVG, makeAbsolute } = require('svg-path-parser');

const {
  getCharacterData,
  generateFullArrowPath,
  interpolateMedianPoint
} = require('./generateDirectionalSvgs.js');

// Dimensions (in mm)
const PLATE_SIZE_MM = 101.6; // 4 inches
const PLATE_HEIGHT_MM = 4;
const RECESS_START_MM = 0.5;
const RECESS_DEPTH_MM = 3.5; // Goes from 0.5mm to 4mm (full depth)
const CORNER_RADIUS_MM = 8;
const SVG_SIZE = 1024; // SVG viewBox size

// Scale factor from SVG units to mm
const SCALE = PLATE_SIZE_MM / SVG_SIZE;

/**
 * Convert SVG path commands to polygon points
 * Approximates curves with line segments
 */
function pathToPolygon(pathData, samplesPerCurve = 10) {
  const commands = makeAbsolute(parseSVG(pathData));
  const points = [];
  let currentX = 0, currentY = 0;
  let startX = 0, startY = 0;

  for (const cmd of commands) {
    switch (cmd.code) {
      case 'M':
        currentX = cmd.x;
        currentY = cmd.y;
        startX = currentX;
        startY = currentY;
        points.push([currentX, currentY]);
        break;

      case 'L':
        currentX = cmd.x;
        currentY = cmd.y;
        points.push([currentX, currentY]);
        break;

      case 'Q': // Quadratic Bezier
        for (let t = 1; t <= samplesPerCurve; t++) {
          const tt = t / samplesPerCurve;
          const x = (1 - tt) * (1 - tt) * currentX + 2 * (1 - tt) * tt * cmd.x1 + tt * tt * cmd.x;
          const y = (1 - tt) * (1 - tt) * currentY + 2 * (1 - tt) * tt * cmd.y1 + tt * tt * cmd.y;
          points.push([x, y]);
        }
        currentX = cmd.x;
        currentY = cmd.y;
        break;

      case 'C': // Cubic Bezier
        for (let t = 1; t <= samplesPerCurve; t++) {
          const tt = t / samplesPerCurve;
          const mt = 1 - tt;
          const x = mt * mt * mt * currentX + 3 * mt * mt * tt * cmd.x1 + 3 * mt * tt * tt * cmd.x2 + tt * tt * tt * cmd.x;
          const y = mt * mt * mt * currentY + 3 * mt * mt * tt * cmd.y1 + 3 * mt * tt * tt * cmd.y2 + tt * tt * tt * cmd.y;
          points.push([x, y]);
        }
        currentX = cmd.x;
        currentY = cmd.y;
        break;

      case 'Z':
        if (points.length > 0 && (points[points.length - 1][0] !== startX || points[points.length - 1][1] !== startY)) {
          points.push([startX, startY]);
        }
        break;
    }
  }

  return points;
}

/**
 * Convert SVG coordinates to 3D model coordinates
 * SVG uses transform="scale(1, -1) translate(0, -900)" which flips Y
 * We mirror X to get correct orientation in OpenSCAD
 */
function svgToModelCoords(x, y) {
  // Mirror X to fix orientation, transform Y to account for SVG flip
  const modelX = (SVG_SIZE - x) * SCALE;  // Mirror horizontally
  const modelY = (900 - y) * SCALE;       // Account for SVG Y transform
  return [modelX, modelY];
}

/**
 * Calculate median length for adaptive positioning
 */
function getMedianLength(median) {
  let totalLength = 0;
  for (let i = 1; i < median.length; i++) {
    const [x1, y1] = median[i - 1];
    const [x2, y2] = median[i];
    totalLength += Math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2);
  }
  return totalLength;
}

/**
 * Simple moving average smoothing
 * @param {Array<Array<number>>} points - Points to smooth [[x,y], ...]
 * @param {number} windowSize - Number of points to average (should be odd)
 * @returns {Array<Array<number>>} Smoothed points
 */
function movingAverageSmooth(points, windowSize = 5) {
  if (points.length < windowSize) return points;

  const halfWindow = Math.floor(windowSize / 2);
  const result = [];

  for (let i = 0; i < points.length; i++) {
    let sumX = 0, sumY = 0, count = 0;
    for (let j = Math.max(0, i - halfWindow); j <= Math.min(points.length - 1, i + halfWindow); j++) {
      sumX += points[j][0];
      sumY += points[j][1];
      count++;
    }
    result.push([sumX / count, sumY / count]);
  }

  return result;
}

/**
 * Generate OpenSCAD code for a character
 * This can be compiled to STL using OpenSCAD CLI
 */
function generateOpenScad(char, options = {}) {
  const data = getCharacterData(char);
  if (!data) {
    return null;
  }

  const { strokes, medians } = data;
  const arrowSize = options.arrowSize || 14;
  const arrowLineWidth = 3.0; // Width of arrow line in SVG units (~32% of typical stroke width)
  const romanization = options.romanization || null;

  // Plate dimensions - taller if romanization is present
  const plateWidth = PLATE_SIZE_MM;
  const romanAreaHeight = 20; // Space for romanization text at bottom (mm)
  const plateHeight = romanization ? PLATE_SIZE_MM + romanAreaHeight : PLATE_SIZE_MM;
  const romanTextSize = 6; // Text size in mm (smaller for more padding)
  const romanTextY = 12; // Distance from bottom edge to text center (mm) - more padding

  let scadCode = `// OpenSCAD file for character: ${char}
// Generated by generateStl.js
// Compile with: openscad -o output.stl input.scad

$fn = 32; // Smoothness for curves

// Dimensions
plate_width = ${plateWidth.toFixed(2)};
plate_height_y = ${plateHeight.toFixed(2)};
plate_height_z = ${PLATE_HEIGHT_MM};
recess_start = ${RECESS_START_MM};
corner_radius = ${CORNER_RADIUS_MM};

// Main module
module character_tile() {
    difference() {
        // Base plate with rounded corners
        rounded_plate();

        // Recessed character strokes (inlay color)
        // Character is shifted up to make room for romanization below
        translate([0, ${romanization ? romanAreaHeight.toFixed(2) : 0}, recess_start])
            linear_extrude(height = plate_height_z)
                character_strokes();

        // Recessed arrows and numbers at SAME depth as strokes (base plate color)
        // These cut through the stroke inlay to show base plate color
        translate([0, ${romanization ? romanAreaHeight.toFixed(2) : 0}, recess_start])
            linear_extrude(height = plate_height_z)
                arrows_and_numbers();
${romanization ? `
        // Recessed romanization text (same color as strokes)
        translate([0, 0, recess_start])
            linear_extrude(height = plate_height_z)
                romanization_text();
` : ''}
    }
}

// Rounded rectangle plate
module rounded_plate() {
    linear_extrude(height = plate_height_z)
        offset(r = corner_radius)
            offset(r = -corner_radius)
                square([plate_width, plate_height_y]);
}
${romanization ? `
// Romanization text (positioned at bottom of tile visually)
module romanization_text() {
    translate([plate_width / 2, plate_height_y - ${romanTextY}])
        rotate([0, 0, 180])
            text("${romanization}", size=${romanTextSize}, halign="center", valign="center", font="Arial:style=Bold");
}
` : ''}

// Character strokes only
module character_strokes() {
    union() {
`;

  // Add each stroke as a polygon
  for (let i = 0; i < strokes.length; i++) {
    const strokePath = strokes[i];
    const points = pathToPolygon(strokePath);

    if (points.length > 2) {
      scadCode += `        // Stroke ${i + 1}\n`;
      scadCode += `        polygon([\n`;
      for (let j = 0; j < points.length; j++) {
        const [x, y] = svgToModelCoords(points[j][0], points[j][1]);
        scadCode += `            [${x.toFixed(3)}, ${y.toFixed(3)}]${j < points.length - 1 ? ',' : ''}\n`;
      }
      scadCode += `        ]);\n\n`;
    }
  }

  scadCode += `    }
}

// Arrows and numbers (white inlay)
module arrows_and_numbers() {
    union() {
`;

  // Add arrows and numbers for each stroke
  for (let i = 0; i < strokes.length; i++) {
    const median = medians[i];
    const strokeNum = i + 1;
    const strokeLength = getMedianLength(median);

    // Adaptive positioning (same logic as printable SVG)
    let numberPercent, arrowStartPercent;
    if (strokeLength < 150) {
      numberPercent = 0.30;
      arrowStartPercent = 0.45;
    } else if (strokeLength < 400) {
      numberPercent = 0.15;
      arrowStartPercent = 0.25;
    } else {
      numberPercent = 0.08;
      arrowStartPercent = 0.15;
    }

    const arrowTipPercent = 0.95;

    // Number position
    const numberPos = interpolateMedianPoint(median, numberPercent);
    const [numX, numY] = svgToModelCoords(numberPos[0], numberPos[1]);

    // Add stroke number (30px in SVG = ~3mm in model)
    // Mirror the text since our coordinate system mirrors X
    const textSize = 30 * SCALE;
    scadCode += `        // Number ${strokeNum}\n`;
    scadCode += `        translate([${numX.toFixed(3)}, ${numY.toFixed(3)}])\n`;
    scadCode += `            rotate([0, 0, 180])\n`;
    scadCode += `                text("${strokeNum}", size=${textSize.toFixed(2)}, halign="center", valign="center", font="Arial:style=Bold");\n\n`;

    // Build arrow line as a thick path (series of circles connected)
    scadCode += `        // Arrow ${strokeNum}\n`;

    // Sample arrow points finely from the median
    const rawArrowPoints = [];
    for (let t = arrowStartPercent; t <= arrowTipPercent - 0.02; t += 0.01) {
      rawArrowPoints.push(interpolateMedianPoint(median, t));
    }

    // Arrow tip and direction
    const arrowTipPoint = interpolateMedianPoint(median, arrowTipPercent);
    const directionPoint = interpolateMedianPoint(median, arrowTipPercent - 0.08);
    const dx = arrowTipPoint[0] - directionPoint[0];
    const dy = arrowTipPoint[1] - directionPoint[1];
    const len = Math.sqrt(dx * dx + dy * dy);
    const dirX = len > 0 ? dx / len : 1;
    const dirY = len > 0 ? dy / len : 0;

    // Arrowhead base (used for arrowhead polygon, NOT for smoothed line)
    const baseX = arrowTipPoint[0] - dirX * arrowSize;
    const baseY = arrowTipPoint[1] - dirY * arrowSize;

    // Apply moving average smoothing (multiple passes for extra smoothness)
    let smoothedPoints = movingAverageSmooth(rawArrowPoints, 7);
    smoothedPoints = movingAverageSmooth(smoothedPoints, 5);
    smoothedPoints = movingAverageSmooth(smoothedPoints, 3);

    // Create arrow line as sequential hulls between point pairs (follows curve properly)
    const lineRadius = (arrowLineWidth / 2 * SCALE).toFixed(3);
    for (let j = 0; j < smoothedPoints.length - 1; j++) {
      const [px1, py1] = svgToModelCoords(smoothedPoints[j][0], smoothedPoints[j][1]);
      const [px2, py2] = svgToModelCoords(smoothedPoints[j + 1][0], smoothedPoints[j + 1][1]);
      scadCode += `        hull() { translate([${px1.toFixed(3)}, ${py1.toFixed(3)}]) circle(r=${lineRadius}); translate([${px2.toFixed(3)}, ${py2.toFixed(3)}]) circle(r=${lineRadius}); }\n`;
    }

    // Arrowhead
    const headWidth = arrowSize * 0.7;
    const perpX = -dirY;
    const perpY = dirX;
    const tipX = arrowTipPoint[0];
    const tipY = arrowTipPoint[1];
    const wing1X = baseX + perpX * (headWidth / 2);
    const wing1Y = baseY + perpY * (headWidth / 2);
    const wing2X = baseX - perpX * (headWidth / 2);
    const wing2Y = baseY - perpY * (headWidth / 2);

    const [mTipX, mTipY] = svgToModelCoords(tipX, tipY);
    const [mWing1X, mWing1Y] = svgToModelCoords(wing1X, wing1Y);
    const [mWing2X, mWing2Y] = svgToModelCoords(wing2X, wing2Y);

    scadCode += `        // Arrowhead ${strokeNum}\n`;
    scadCode += `        polygon([[${mTipX.toFixed(3)}, ${mTipY.toFixed(3)}], [${mWing1X.toFixed(3)}, ${mWing1Y.toFixed(3)}], [${mWing2X.toFixed(3)}, ${mWing2Y.toFixed(3)}]]);\n\n`;
  }

  scadCode += `    }
}

// Render the tile
character_tile();
`;

  return scadCode;
}

/**
 * Generate a simple binary STL file
 * Creates a flat representation suitable for laser cutting or simple 3D printing
 */
function generateBinaryStl(char, options = {}) {
  const data = getCharacterData(char);
  if (!data) {
    return null;
  }

  const { strokes, medians } = data;
  const triangles = [];

  // Helper to add a triangle
  function addTriangle(v1, v2, v3, normal = [0, 0, 1]) {
    triangles.push({ normal, vertices: [v1, v2, v3] });
  }

  // Create base plate triangles (simplified - just a rectangle)
  const baseZ = 0;
  const topZ = RECESS_START_MM;
  const recessZ = PLATE_HEIGHT_MM;

  // Base bottom face
  addTriangle(
    [0, 0, baseZ],
    [PLATE_SIZE_MM, 0, baseZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ],
    [0, 0, -1]
  );
  addTriangle(
    [0, 0, baseZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ],
    [0, PLATE_SIZE_MM, baseZ],
    [0, 0, -1]
  );

  // Base top face (where recess isn't)
  addTriangle(
    [0, 0, topZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, topZ],
    [PLATE_SIZE_MM, 0, topZ],
    [0, 0, 1]
  );
  addTriangle(
    [0, 0, topZ],
    [0, PLATE_SIZE_MM, topZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, topZ],
    [0, 0, 1]
  );

  // Side faces
  // Front
  addTriangle([0, 0, baseZ], [PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, 0, recessZ], [0, -1, 0]);
  addTriangle([0, 0, baseZ], [PLATE_SIZE_MM, 0, recessZ], [0, 0, recessZ], [0, -1, 0]);
  // Back
  addTriangle([0, PLATE_SIZE_MM, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ], [0, 1, 0]);
  addTriangle([0, PLATE_SIZE_MM, baseZ], [0, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [0, 1, 0]);
  // Left
  addTriangle([0, 0, baseZ], [0, 0, recessZ], [0, PLATE_SIZE_MM, recessZ], [-1, 0, 0]);
  addTriangle([0, 0, baseZ], [0, PLATE_SIZE_MM, recessZ], [0, PLATE_SIZE_MM, baseZ], [-1, 0, 0]);
  // Right
  addTriangle([PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, 0, recessZ], [1, 0, 0]);
  addTriangle([PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [1, 0, 0]);

  // Create binary STL buffer
  const headerSize = 80;
  const triangleCount = triangles.length;
  const triangleSize = 50; // 12 floats * 4 bytes + 2 bytes attribute
  const bufferSize = headerSize + 4 + triangleCount * triangleSize;

  const buffer = Buffer.alloc(bufferSize);
  let offset = 0;

  // Header (80 bytes)
  buffer.write(`STL for character ${char}`, 0);
  offset = 80;

  // Triangle count (4 bytes)
  buffer.writeUInt32LE(triangleCount, offset);
  offset += 4;

  // Write each triangle
  for (const tri of triangles) {
    // Normal vector (3 floats)
    buffer.writeFloatLE(tri.normal[0], offset); offset += 4;
    buffer.writeFloatLE(tri.normal[1], offset); offset += 4;
    buffer.writeFloatLE(tri.normal[2], offset); offset += 4;

    // Vertices (9 floats)
    for (const v of tri.vertices) {
      buffer.writeFloatLE(v[0], offset); offset += 4;
      buffer.writeFloatLE(v[1], offset); offset += 4;
      buffer.writeFloatLE(v[2], offset); offset += 4;
    }

    // Attribute byte count (2 bytes)
    buffer.writeUInt16LE(0, offset); offset += 2;
  }

  return buffer;
}

/**
 * Generate STL files for a character
 * Creates both OpenSCAD source and a simplified STL
 */
function generateStlFiles(char, outputDir, options = {}) {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const charCode = char.charCodeAt(0);

  // Generate OpenSCAD file (can be compiled to proper STL)
  const scadCode = generateOpenScad(char, options);
  if (scadCode) {
    const scadPath = path.join(outputDir, `${charCode}-tile.scad`);
    fs.writeFileSync(scadPath, scadCode);
    console.log(`Generated OpenSCAD: ${scadPath}`);
  }

  // Generate simplified binary STL (base plate only for now)
  const stlBuffer = generateBinaryStl(char, options);
  if (stlBuffer) {
    const stlPath = path.join(outputDir, `${charCode}-base.stl`);
    fs.writeFileSync(stlPath, stlBuffer);
    console.log(`Generated STL base: ${stlPath}`);
  }

  return { scadCode, stlBuffer };
}

// CLI entry point
if (require.main === module) {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log('Usage: node generateStl.js <character> [outputDir]');
    console.log('       node generateStl.js --batch <char1,char2,...> [outputDir]');
    console.log('');
    console.log('Generates OpenSCAD (.scad) files that can be compiled to STL');
    console.log('using: openscad -o output.stl input.scad');
    process.exit(1);
  }

  let outputDir = path.join(__dirname, '..', 'output');

  if (args[0] === '--batch') {
    const chars = args[1].split(',');
    if (args[2]) outputDir = args[2];
    for (const char of chars) {
      generateStlFiles(char, outputDir);
    }
  } else {
    const char = args[0];
    if (args[1]) outputDir = args[1];
    generateStlFiles(char, outputDir);
  }
}

module.exports = {
  generateOpenScad,
  generateBinaryStl,
  generateStlFiles,
  pathToPolygon,
  svgToModelCoords
};
