#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { parseSVG, makeAbsolute } = require('svg-path-parser');

const {
  getCharacterData,
  generateFullArrowPath
} = require('./generateDirectionalSvgs.js');

// Dimensions (in mm)
const PLATE_SIZE_MM = 101.6; // 4 inches
const PLATE_HEIGHT_MM = 4;
const RECESS_START_MM = 0.5;
const RECESS_DEPTH_MM = 3.5; // Goes from 0.5mm to 4mm (full depth)
const CORNER_RADIUS_MM = 8;
const SVG_SIZE = 1024; // SVG viewBox size

// Scale factor from SVG units to mm
const SCALE = PLATE_SIZE_MM / SVG_SIZE;

/**
 * Convert SVG path commands to polygon points
 * Approximates curves with line segments
 */
function pathToPolygon(pathData, samplesPerCurve = 10) {
  const commands = makeAbsolute(parseSVG(pathData));
  const points = [];
  let currentX = 0, currentY = 0;
  let startX = 0, startY = 0;

  for (const cmd of commands) {
    switch (cmd.code) {
      case 'M':
        currentX = cmd.x;
        currentY = cmd.y;
        startX = currentX;
        startY = currentY;
        points.push([currentX, currentY]);
        break;

      case 'L':
        currentX = cmd.x;
        currentY = cmd.y;
        points.push([currentX, currentY]);
        break;

      case 'Q': // Quadratic Bezier
        for (let t = 1; t <= samplesPerCurve; t++) {
          const tt = t / samplesPerCurve;
          const x = (1 - tt) * (1 - tt) * currentX + 2 * (1 - tt) * tt * cmd.x1 + tt * tt * cmd.x;
          const y = (1 - tt) * (1 - tt) * currentY + 2 * (1 - tt) * tt * cmd.y1 + tt * tt * cmd.y;
          points.push([x, y]);
        }
        currentX = cmd.x;
        currentY = cmd.y;
        break;

      case 'C': // Cubic Bezier
        for (let t = 1; t <= samplesPerCurve; t++) {
          const tt = t / samplesPerCurve;
          const mt = 1 - tt;
          const x = mt * mt * mt * currentX + 3 * mt * mt * tt * cmd.x1 + 3 * mt * tt * tt * cmd.x2 + tt * tt * tt * cmd.x;
          const y = mt * mt * mt * currentY + 3 * mt * mt * tt * cmd.y1 + 3 * mt * tt * tt * cmd.y2 + tt * tt * tt * cmd.y;
          points.push([x, y]);
        }
        currentX = cmd.x;
        currentY = cmd.y;
        break;

      case 'Z':
        if (points.length > 0 && (points[points.length - 1][0] !== startX || points[points.length - 1][1] !== startY)) {
          points.push([startX, startY]);
        }
        break;
    }
  }

  return points;
}

/**
 * Convert SVG coordinates to 3D model coordinates
 * SVG has Y inverted and uses different scale
 */
function svgToModelCoords(x, y) {
  // SVG coordinate system: origin top-left, Y increases downward
  // But our SVG uses transform="scale(1, -1) translate(0, -900)"
  // So we need to account for that
  const modelX = x * SCALE;
  const modelY = (900 - y) * SCALE; // Flip Y and offset
  return [modelX, modelY];
}

/**
 * Generate OpenSCAD code for a character
 * This can be compiled to STL using OpenSCAD CLI
 */
function generateOpenScad(char, options = {}) {
  const data = getCharacterData(char);
  if (!data) {
    return null;
  }

  const { strokes, medians } = data;
  const arrowSize = options.arrowSize || 20;

  let scadCode = `// OpenSCAD file for character: ${char}
// Generated by generateStl.js
// Compile with: openscad -o output.stl input.scad

$fn = 32; // Smoothness for curves

// Dimensions
plate_size = ${PLATE_SIZE_MM};
plate_height = ${PLATE_HEIGHT_MM};
recess_start = ${RECESS_START_MM};
corner_radius = ${CORNER_RADIUS_MM};

// Main module
module character_tile() {
    difference() {
        // Base plate with rounded corners
        rounded_plate();

        // Recessed character and arrows
        translate([0, 0, recess_start])
            linear_extrude(height = plate_height)
                character_shape();
    }
}

// Rounded rectangle plate
module rounded_plate() {
    linear_extrude(height = plate_height)
        offset(r = corner_radius)
            offset(r = -corner_radius)
                square([plate_size, plate_size]);
}

// Character shape (strokes + arrows)
module character_shape() {
    union() {
`;

  // Add each stroke as a polygon
  for (let i = 0; i < strokes.length; i++) {
    const strokePath = strokes[i];
    const points = pathToPolygon(strokePath);

    if (points.length > 2) {
      scadCode += `        // Stroke ${i + 1}\n`;
      scadCode += `        polygon([\n`;
      for (let j = 0; j < points.length; j++) {
        const [x, y] = svgToModelCoords(points[j][0], points[j][1]);
        scadCode += `            [${x.toFixed(3)}, ${y.toFixed(3)}]${j < points.length - 1 ? ',' : ''}\n`;
      }
      scadCode += `        ]);\n\n`;
    }
  }

  scadCode += `    }
}

// Render the tile
character_tile();
`;

  return scadCode;
}

/**
 * Generate a simple binary STL file
 * Creates a flat representation suitable for laser cutting or simple 3D printing
 */
function generateBinaryStl(char, options = {}) {
  const data = getCharacterData(char);
  if (!data) {
    return null;
  }

  const { strokes, medians } = data;
  const triangles = [];

  // Helper to add a triangle
  function addTriangle(v1, v2, v3, normal = [0, 0, 1]) {
    triangles.push({ normal, vertices: [v1, v2, v3] });
  }

  // Create base plate triangles (simplified - just a rectangle)
  const baseZ = 0;
  const topZ = RECESS_START_MM;
  const recessZ = PLATE_HEIGHT_MM;

  // Base bottom face
  addTriangle(
    [0, 0, baseZ],
    [PLATE_SIZE_MM, 0, baseZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ],
    [0, 0, -1]
  );
  addTriangle(
    [0, 0, baseZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ],
    [0, PLATE_SIZE_MM, baseZ],
    [0, 0, -1]
  );

  // Base top face (where recess isn't)
  addTriangle(
    [0, 0, topZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, topZ],
    [PLATE_SIZE_MM, 0, topZ],
    [0, 0, 1]
  );
  addTriangle(
    [0, 0, topZ],
    [0, PLATE_SIZE_MM, topZ],
    [PLATE_SIZE_MM, PLATE_SIZE_MM, topZ],
    [0, 0, 1]
  );

  // Side faces
  // Front
  addTriangle([0, 0, baseZ], [PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, 0, recessZ], [0, -1, 0]);
  addTriangle([0, 0, baseZ], [PLATE_SIZE_MM, 0, recessZ], [0, 0, recessZ], [0, -1, 0]);
  // Back
  addTriangle([0, PLATE_SIZE_MM, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ], [0, 1, 0]);
  addTriangle([0, PLATE_SIZE_MM, baseZ], [0, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [0, 1, 0]);
  // Left
  addTriangle([0, 0, baseZ], [0, 0, recessZ], [0, PLATE_SIZE_MM, recessZ], [-1, 0, 0]);
  addTriangle([0, 0, baseZ], [0, PLATE_SIZE_MM, recessZ], [0, PLATE_SIZE_MM, baseZ], [-1, 0, 0]);
  // Right
  addTriangle([PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [PLATE_SIZE_MM, 0, recessZ], [1, 0, 0]);
  addTriangle([PLATE_SIZE_MM, 0, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, baseZ], [PLATE_SIZE_MM, PLATE_SIZE_MM, recessZ], [1, 0, 0]);

  // Create binary STL buffer
  const headerSize = 80;
  const triangleCount = triangles.length;
  const triangleSize = 50; // 12 floats * 4 bytes + 2 bytes attribute
  const bufferSize = headerSize + 4 + triangleCount * triangleSize;

  const buffer = Buffer.alloc(bufferSize);
  let offset = 0;

  // Header (80 bytes)
  buffer.write(`STL for character ${char}`, 0);
  offset = 80;

  // Triangle count (4 bytes)
  buffer.writeUInt32LE(triangleCount, offset);
  offset += 4;

  // Write each triangle
  for (const tri of triangles) {
    // Normal vector (3 floats)
    buffer.writeFloatLE(tri.normal[0], offset); offset += 4;
    buffer.writeFloatLE(tri.normal[1], offset); offset += 4;
    buffer.writeFloatLE(tri.normal[2], offset); offset += 4;

    // Vertices (9 floats)
    for (const v of tri.vertices) {
      buffer.writeFloatLE(v[0], offset); offset += 4;
      buffer.writeFloatLE(v[1], offset); offset += 4;
      buffer.writeFloatLE(v[2], offset); offset += 4;
    }

    // Attribute byte count (2 bytes)
    buffer.writeUInt16LE(0, offset); offset += 2;
  }

  return buffer;
}

/**
 * Generate STL files for a character
 * Creates both OpenSCAD source and a simplified STL
 */
function generateStlFiles(char, outputDir, options = {}) {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const charCode = char.charCodeAt(0);

  // Generate OpenSCAD file (can be compiled to proper STL)
  const scadCode = generateOpenScad(char, options);
  if (scadCode) {
    const scadPath = path.join(outputDir, `${charCode}-tile.scad`);
    fs.writeFileSync(scadPath, scadCode);
    console.log(`Generated OpenSCAD: ${scadPath}`);
  }

  // Generate simplified binary STL (base plate only for now)
  const stlBuffer = generateBinaryStl(char, options);
  if (stlBuffer) {
    const stlPath = path.join(outputDir, `${charCode}-base.stl`);
    fs.writeFileSync(stlPath, stlBuffer);
    console.log(`Generated STL base: ${stlPath}`);
  }

  return { scadCode, stlBuffer };
}

// CLI entry point
if (require.main === module) {
  const args = process.argv.slice(2);

  if (args.length === 0) {
    console.log('Usage: node generateStl.js <character> [outputDir]');
    console.log('       node generateStl.js --batch <char1,char2,...> [outputDir]');
    console.log('');
    console.log('Generates OpenSCAD (.scad) files that can be compiled to STL');
    console.log('using: openscad -o output.stl input.scad');
    process.exit(1);
  }

  let outputDir = path.join(__dirname, '..', 'output');

  if (args[0] === '--batch') {
    const chars = args[1].split(',');
    if (args[2]) outputDir = args[2];
    for (const char of chars) {
      generateStlFiles(char, outputDir);
    }
  } else {
    const char = args[0];
    if (args[1]) outputDir = args[1];
    generateStlFiles(char, outputDir);
  }
}

module.exports = {
  generateOpenScad,
  generateBinaryStl,
  generateStlFiles,
  pathToPolygon,
  svgToModelCoords
};
